export enum AuditAction {
  USER_REGISTER = 'auth.register',
  AUTH_LOGIN = 'auth.login',
  AUTH_CHANGE_PASSWORD = 'auth.change_password',
  AUTH_FORGOT_PASSWORD = 'auth.forgot_password',
  AUTH_RESET_PASSWORD = 'auth.reset_password',
  AUTH_LOGOUT = 'auth.logout',
  AUTH_VERIFY_EMAIL = 'auth.verify_email',
  AUTH_RESEND_VERIFY_EMAIL = 'auth.resend_verify_email',
  AUTH_REFRESH = 'auth.refresh_token',
  ORG_UPDATED = 'org.updated',
  MEMBER_INVITED = 'member.invited',
  MEMBER_INVITE_ACCEPTED = 'member.invite_accepted',
  MEMBER_ROLE_UPDATED = 'member.role_updated',
  MEMBER_UPDATED = 'member.updated',
  MEMBER_EMAIL_UPDATED = 'member.email_updated',
  MEMBER_REMOVED = 'member.removed',
  API_KEY_CREATED = 'apikey.created',
  API_KEY_REVOKED = 'apikey.revoked',
  PLAN_LIMIT_EXCEEDED = 'plan.limit_exceeded',
  WEBHOOK_CREATED = 'webhook.created',
  WEBHOOK_DELIVERED = 'webhook.delivered',
  WEBHOOK_DELETED = 'webhook.deleted',
}
